INSERT INTO Animals (ImageID, SoundID, Shiny, FunFact)
VALUES
(7, 4, 0,  'Elephants use their feet to feel sound vibrations'),
(8, 6, 0,  'A newborn giraffe is taller than most humans'),
(9, 7, 0,  'A hippopotamus can hold its breath for five minutes'),
(10, 8, 0, 'Monkeys show affection by grooming each other'),
(11, 9, 0, 'Pandas spend up to half their day eating'),
(12, 10, 0, 'Parrots taste food with the top of their beaks'),
(13, 11, 0, 'Penguins can slide on their bellies'),
(14, 12, 0, 'Pigs roll around in mud to cool off when they''re hot'),
(15, 14, 0, 'Baby rabbits are born with their eyes close and without fur'),
(16, 15, 0, 'Some snakes play dead when an enemy is close'),
(17, 4, 1, 'Elephants use their trunks to greet each other and hug'),
(18, 6, 1, 'Giraffes sleep standing up'),
(19, 7, 1, 'The name hippopotamus means ''river horse'''),
(20, 8, 1, 'Monkeys use their long strong arms to swing from branches'),
(21, 9, 1, 'Baby pandas are born pink and are the size of a pencil'),
(22, 10, 1, 'The heaviest parrot weighs as much as a cat'),
(23, 11, 1, 'Penguins have wings but can''t fly'),
(24, 12, 1, 'A mother pig can have eight to twelve babies at a time'),
(25, 14, 1, 'Rabbits live in holes in the ground called ''burrows'''),
(26, 15, 1, 'Snakes shed their skin when they get bigger and grow new skin'),
(29, 1, 0, 'Bears have two layers of fur'),
(30, 5, 0, 'Clownfish sleep with their eyes open because they don''t have eyelids'),
(31, 3, 0, 'Dogs have powerful noses and can smell things that people can''t smell'),
(32, 16, 0, 'The killer whale is not actually a whale, it is a type of dolphin'),
(33, 2, 0, 'Most cats sleep sixteen to eighteen hours a day'),
(34, 13, 0, 'Polar bears are the only bear to only eat meat'),
(35, 1, 1, 'Most bears are omnivores, meaning they eat meat and plants'),
(36, 5, 1, 'Clownfish sleep and hide in plantlike creatures called anemones'),
(37, 3, 1, 'The pads on the bottom of a dog''s feet help protect their feet'),
(38, 16, 1, 'Killer whales eat sharks and other sea creatures'),
(39, 2, 1, 'A cat''s whiskers help it find its way in the dark'),
(40, 13, 1, 'Polar bears clean their fur by rolling around in the snow'),
(41, 23, 0, 'Rhinos have poor eyesight but a very good sense of smell and hearing'),
(42, 19, 0, 'Crabs can use their claws for cutting, crushing, and picking up food'),
(43, 17, 0, 'Baby butterflies hatch from eggs and start life as caterpillars'),
(44, 21, 0, 'Lions are the second largest type of cat, tigers are the largest'),
(45, 24, 0, 'Squirrels love acorns, they bury the nuts in the ground to eat later'),
(46, 22, 0, 'Meerkats build huge underground homes called burrows'),
(47, 18, 0, 'Cows chew their food before and after they swallow it'),
(48, 20, 0, 'Frogs absorb water through their skin so they don''t need to drink'),
(49, 23, 1, 'Rhinoceros are herbivores, meaning they only eat plants'),
(50, 19, 1, 'The Coconut crab lives on land and can climb trees'),
(51, 17, 1, 'Caterpillars make a hard shell called a chrysalis to turn into butterflies'),
(52, 21, 1, 'Lions hunt large animals, such as zebra and they hunt at night'),
(53, 24, 1, 'Squirrels build their nests high up in trees to keep safe'),
(54, 22, 1, 'Meerkats live together in big groups called ''mobs'''),
(55, 18, 1, 'A cow''s stomach has four seperate parts, human stomachs only have one'),
(56, 20, 1, 'A frog''s nose and eyes are on top of its head so it can see when in water');