INSERT INTO Animals (ImageID, SoundID, Shiny, FunFact)
VALUES
(7, 6, 0, 'Frogs breathe through their skin'),
(8, 2, 0, 'A newborn elephant can weigh up to 200 pounds'),
(9, 5, 0, 'Dogs can hear noises that humans can''t hear'),
(9, 5, 1, 'Scientists believe that dogs have dreams like people'),
(10, 2, 0, 'Crabs have 10 legs'),
(10, 2, 1, 'The Japanese Spider Crab''s legs are up to 12 feet long'),
(11, 8, 0, 'The Balloon Dog''s favorite food it air'),
(12, 3, 0, 'Fish have gills to breathe under water'),
(12, 3, 1, 'Sharks are fish'),
(13, 2, 0, 'Cheetahs can run as fast as 75 miles per hour for short periods of time'),
(14, 10, 0, 'monkeys show affection by grooming each other'),
(15, 4, 0, 'The milk we drink comes from dairy cows'),
(16, 7, 0, 'A zebra''s stripes help protect them from danger'),
(17, 9, 0, 'The name rhinoceros means ''nose horn'''),
(18, 11, 0, 'The name hippopotamus means ''river horse'''),
(19, 7, 0, 'Male deer are called bucks and grow new antlers every year'),
(20, 9, 0, 'A polar bear has black skin and looks whites because it''s fur is see through'),
(20, 9, 1, 'The polar bear is the largest meat eating animal that lives on land'),
(21, 3, 0, 'A mouse has a pointed nose, round ears, and their tails have little hair'),
(22, 3, 0, 'Badgers are nocturnal, they sleep during the day and are awake at night'),
(23, 7, 0, 'horses can sleep lying down and standing up'),
(23, 7, 1, 'Newborn horses, called foals, can run shortly after being born'),
(24, 6, 0, 'Seals spend most of their lives in the water'),
(25, 11, 0, 'A Rock Hopper penguin can jump up to 5 feet high'),
(26, 3, 0, 'Giant squids are the fastest squids in the sea');