--INSERT INTO GameCategories (GameCategoryName)
--VALUES
--('reading:letter recognition'),     
--('math:number recognition'),		
--('math:shape recognition'),		  
--('reading:sorting'),				
--('reading:sight word recognition'),	
--('math:counting'),				  
--('math:addition');	